run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
