apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopping-cart-apps

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: shopping-cart

images:
  - name: shopping-cart-basket
    newName: ghcr.io/wilddog64/shopping-cart-basket
    newTag: sha-a7f60967bf6b9ff547de803e20234ac521ebb669
