apiVersion: v1
kind: Service
metadata:
  name: basket-service
  labels:
    app.kubernetes.io/name: basket-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: shopping-cart
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8083
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: basket-service
