---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: basket-service
  labels:
    app.kubernetes.io/name: basket-service
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: shopping-cart
